apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.nginx }}
          env:
            - name: LISTEN_PORT
              value: "{{ .Values.env.nginx.LISTEN_PORT }}"
            - name: API_BACKEND
              value: "{{ .Values.env.nginx.API_BACKEND }}"
            - name: TERMINAL_BACKEND
              value: "{{ .Values.env.nginx.TERMINAL_BACKEND }}"
            - name: FRONTEND_BACKEND
              value: "{{ .Values.env.nginx.FRONTEND_BACKEND }}"
          ports:
            - containerPort: {{ .Values.service.nginx.port }}






