apiVersion: apps/v1
kind: Deployment
metadata:
  name: gripo-application
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gripo-application
  template:
    metadata:
      labels:
        app: gripo-application
    spec:
      containers:
        - name: gripo-application
          image: {{ .Values.image.gripoApplication }}
          env:
            - name: GRIPO_SERVER_ADDRESS
              value: "{{ .Values.env.gripoApplication.GRIPO_SERVER_ADDRESS }}"
          ports:
            - containerPort: {{ .Values.service.gripoApplication.port }}




