apiVersion: apps/v1
kind: Deployment
metadata:
  name: gripo-terminal
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gripo-terminal
  template:
    metadata:
      labels:
        app: gripo-terminal
    spec:
      containers:
        - name: gripo-terminal
          image: {{ .Values.image.gripoTerminal }}
          ports:
            - containerPort: {{ .Values.service.gripoTerminal.port }}
