apiVersion: apps/v1
kind: Deployment
metadata:
  name: gripo-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gripo-frontend
  template:
    metadata:
      labels:
        app: gripo-frontend
    spec:
      containers:
        - name: gripo-frontend
          image: {{ .Values.image.gripoFrontend }}
          ports:
            - containerPort: {{ .Values.service.gripoFrontend.port }}
