apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.nginx.type }}
  ports:
    - port: {{ .Values.service.nginx.port }}
      targetPort: {{ .Values.service.nginx.port }}
  selector:
    app: nginx



